#!/bin/sh
# Assemble the OpenCloud proxy routes and the compose file list from every app
# enabled under ./apps-enabled, so adding an app is: drop its folder in, run this,
# bring the stack up. Solves the "proxy.yaml is a single file" problem by merging
# each app's route fragment into one generated proxy.yaml.
#
# Usage (from your opencloud-compose checkout, with this kit unpacked into it):
#   1. Enable an app:   cp -r apps-available/<app> apps-enabled/   (or symlink)
#   2. ./assemble.sh
#   3. ./apps-up.sh                # or use the printed docker compose command
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
ENABLED="$ROOT/apps-enabled"
PROXY_OUT="$ROOT/config/opencloud/proxy.yaml"

mkdir -p "$(dirname "$PROXY_OUT")"

# 1. Merge every enabled app's route fragment into one proxy.yaml. Each app's
#    routes.yaml holds only the bare list of route entries (items at column 0);
#    we indent them under a single additional_policies/default/routes block.
{
  echo "# Generated by assemble.sh - do not edit by hand. Edit apps' routes.yaml."
  echo "additional_policies:"
  echo "  - name: default"
  echo "    routes:"
  for d in "$ENABLED"/*/; do
    [ -f "$d/routes.yaml" ] || continue
    echo "      # --- $(basename "$d") ---"
    sed 's/^/      /' "$d/routes.yaml"
  done
} > "$PROXY_OUT"

# 2. Build the compose file list: base + the proxy mount + each app's overlay.
FILES="docker-compose.yml:apps.compose.yml"
COUNT=0
for d in "$ENABLED"/*/; do
  [ -f "$d/app.yml" ] || continue
  FILES="$FILES:apps-enabled/$(basename "$d")/app.yml"
  COUNT=$((COUNT + 1))
done

# Emit a ready-to-run wrapper that doesn't touch your existing .env.
DASH_F=$(printf '%s' "$FILES" | tr ':' '\n' | sed 's/^/-f /' | tr '\n' ' ')
cat > "$ROOT/apps-up.sh" <<EOF
#!/bin/sh
# Generated by assemble.sh - runs docker compose with the enabled apps.
exec docker compose $DASH_F up -d "\$@"
EOF
chmod +x "$ROOT/apps-up.sh"

echo "Enabled apps: $COUNT"
echo "Wrote $PROXY_OUT"
echo "Wrote apps-up.sh"
echo
echo "Bring the stack up with:"
echo "  ./apps-up.sh"
echo "or:"
echo "  docker compose $DASH_F up -d"
